<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<script src="//assets.adobedtm.com/launch-EN68e6921b2a6c4a7ab41dacf4f0cb1eac-development.min.js" async></script>
<script>
    var adminUsageMetadata = {
      "version": "<?= /* @escapeNotVerified */ $block->getMagentoVersion() ?>",
      "user": "<?= /* @escapeNotVerified */ $block->getCurrentUser() ?>",
      "mode": "<?= /* @escapeNotVerified */ $block->getMode() ?>"
    };
</script>
